"""Add missing doctor fields

Revision ID: 0e3cbb9671c3
Revises: 2b160e6b54cc
Create Date: 2025-12-22 21:15:00.175105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3cbb9671c3'
down_revision = '2b160e6b54cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_certifications_id'), 'doctor_certifications', ['id'], unique=False)
    op.add_column('doctors', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('show_certifications_carousel', sa.Boolean(), nullable=True))
    op.drop_constraint('tenant_modules_tenant_id_fkey', 'tenant_modules', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tenant_modules_tenant_id_fkey', 'tenant_modules', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('doctors', 'show_certifications_carousel')
    op.drop_column('doctors', 'subscription_end_date')
    op.drop_column('doctors', 'stripe_customer_id')
    op.drop_index(op.f('ix_doctor_certifications_id'), table_name='doctor_certifications')
    op.drop_table('doctor_certifications')
    # ### end Alembic commands ###

