"""create_preconsultation_templates_table

Revision ID: 20734566c01d
Revises: 9d7a7481285d
Create Date: 2026-01-06 21:50:15.361031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20734566c01d'
down_revision = '9d7a7481285d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preconsultation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preconsultation_templates_id'), 'preconsultation_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preconsultation_templates_id'), table_name='preconsultation_templates')
    op.drop_table('preconsultation_templates')
    # ### end Alembic commands ###

