"""Add reason_for_visit to appointments

Revision ID: 2aad5c62302e
Revises: cf00f917cb5b
Create Date: 2025-11-30 08:14:34.780974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aad5c62302e'
down_revision = 'cf00f917cb5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reason_for_visit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reason_for_visit')
    # ### end Alembic commands ###

