"""Add pdf_config to doctors

Revision ID: 304a348c6ea1
Revises: 5977b81c3b56
Create Date: 2025-12-04 20:30:27.152920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304a348c6ea1'
down_revision = '5977b81c3b56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('pdf_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'pdf_config')
    # ### end Alembic commands ###

