"""add_password_recovery_fields_fix

Revision ID: 3891b5aa1eac
Revises: 9b33ec85782f
Create Date: 2025-12-24 16:47:43.334476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3891b5aa1eac'
down_revision = '9b33ec85782f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'reset_password_expires')
    op.drop_column('doctors', 'reset_password_token')
    # ### end Alembic commands ###

