"""Add design_template to doctor

Revision ID: 42ed74831021
Revises: f228bcf6d2e7
Create Date: 2026-01-02 01:35:50.191236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ed74831021'
down_revision = 'f228bcf6d2e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('design_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'design_template')
    # ### end Alembic commands ###

