"""add_preconsulta_answers_to_appointment

Revision ID: 5977b81c3b56
Revises: 6b2a849d5476
Create Date: 2025-12-03 18:28:56.734983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5977b81c3b56'
down_revision = '6b2a849d5476'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

