"""add universidad to doctors

Revision ID: 6160c7b9aef2
Revises: e1a2b3c4d5e6
Create Date: 2025-12-08 16:17:48.748432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6160c7b9aef2'
down_revision = 'e1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('universidad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'universidad')
    # ### end Alembic commands ###

