"""add_blog_comments

Revision ID: 645ef5e75325
Revises: ba025d6b429c
Create Date: 2025-11-28 13:01:06.295089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645ef5e75325'
down_revision = 'ba025d6b429c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comments_id'), 'blog_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_comments_id'), table_name='blog_comments')
    op.drop_table('blog_comments')
    # ### end Alembic commands ###

