"""Add image_url to locations

Revision ID: 662eb2b34637
Revises: 6f43fd44feab
Create Date: 2025-12-02 15:10:26.164170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662eb2b34637'
down_revision = '6f43fd44feab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'image_url')
    # ### end Alembic commands ###

