"""add_preconsulta_answers_to_appointment

Revision ID: 6b2a849d5476
Revises: 4ece138b14a7
Create Date: 2025-12-03 18:16:34.068179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2a849d5476'
down_revision = '4ece138b14a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('preconsulta_answers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'preconsulta_answers')
    # ### end Alembic commands ###

