"""add_cycle_notifications_and_pregnancy

Revision ID: 7baf1dd5b34a
Revises: 20734566c01d
Create Date: 2026-01-14 14:24:16.115896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baf1dd5b34a'
down_revision = '20734566c01d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_user_id', sa.Integer(), nullable=True),
    sa.Column('contraceptive_enabled', sa.Integer(), nullable=True),
    sa.Column('contraceptive_time', sa.String(), nullable=True),
    sa.Column('contraceptive_frequency', sa.String(), nullable=True),
    sa.Column('rhythm_method_enabled', sa.Integer(), nullable=True),
    sa.Column('fertile_window_alerts', sa.Integer(), nullable=True),
    sa.Column('ovulation_alert', sa.Integer(), nullable=True),
    sa.Column('gyn_checkup_alert', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_user_id'], ['cycle_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_notification_settings_cycle_user_id'), 'cycle_notification_settings', ['cycle_user_id'], unique=True)
    op.create_index(op.f('ix_cycle_notification_settings_id'), 'cycle_notification_settings', ['id'], unique=False)
    op.create_table('pregnancy_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('last_period_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notifications_enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_user_id'], ['cycle_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pregnancy_logs_cycle_user_id'), 'pregnancy_logs', ['cycle_user_id'], unique=False)
    op.create_index(op.f('ix_pregnancy_logs_id'), 'pregnancy_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pregnancy_logs_id'), table_name='pregnancy_logs')
    op.drop_index(op.f('ix_pregnancy_logs_cycle_user_id'), table_name='pregnancy_logs')
    op.drop_table('pregnancy_logs')
    op.drop_index(op.f('ix_cycle_notification_settings_id'), table_name='cycle_notification_settings')
    op.drop_index(op.f('ix_cycle_notification_settings_cycle_user_id'), table_name='cycle_notification_settings')
    op.drop_table('cycle_notification_settings')
    # ### end Alembic commands ###

