"""add_cycle_config_fields

Revision ID: 9b33ec85782f
Revises: 9c8c129fd7ae
Create Date: 2025-12-24 06:32:16.311051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_cycle_config_fields

Revision ID: 9b33ec85782f
Revises: 9c8c129fd7ae
Create Date: 2025-12-24 06:32:16.311051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b33ec85782f'
down_revision = '9c8c129fd7ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle_users', sa.Column('cycle_avg_length', sa.Integer(), nullable=False, server_default='28'))
    op.add_column('cycle_users', sa.Column('period_avg_length', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle_users', 'period_avg_length')
    op.drop_column('cycle_users', 'cycle_avg_length')
    # ### end Alembic commands ###

