"""convert_integer_to_boolean

Revision ID: acfb5f99cde1
Revises: f96bde83783a
Create Date: 2026-01-14 21:11:46.716730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfb5f99cde1'
down_revision = 'f96bde83783a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cycle_notification_settings', 'contraceptive_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='contraceptive_enabled::boolean')
    op.alter_column('cycle_notification_settings', 'rhythm_method_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='rhythm_method_enabled::boolean')
    op.alter_column('cycle_notification_settings', 'fertile_window_alerts',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='fertile_window_alerts::boolean')
    op.alter_column('cycle_notification_settings', 'ovulation_alert',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='ovulation_alert::boolean')
    op.alter_column('cycle_notification_settings', 'gyn_checkup_alert',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='gyn_checkup_alert::boolean')
    op.alter_column('pregnancy_logs', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='is_active::boolean')
    op.alter_column('pregnancy_logs', 'notifications_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='notifications_enabled::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pregnancy_logs', 'notifications_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('pregnancy_logs', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cycle_notification_settings', 'gyn_checkup_alert',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cycle_notification_settings', 'ovulation_alert',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cycle_notification_settings', 'fertile_window_alerts',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cycle_notification_settings', 'rhythm_method_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cycle_notification_settings', 'contraceptive_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###

