"""Add schedule to doctor

Revision ID: 0b061ee0599c
Revises: 2aad5c62302e
Create Date: 2025-12-02 10:21:09.501746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b061ee0599c'
down_revision = '2aad5c62302e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('schedule', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'schedule')
    # ### end Alembic commands ###

