"""add_arko_models

Revision ID: 0b11fb8ec236
Revises: add_assigned_staff_id
Create Date: 2026-06-01 02:02:06.464425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b11fb8ec236'
down_revision = 'add_assigned_staff_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arko_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arko_posts_id'), 'arko_posts', ['id'], unique=False)
    op.create_index(op.f('ix_arko_posts_slug'), 'arko_posts', ['slug'], unique=True)
    op.create_table('arko_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arko_projects_id'), 'arko_projects', ['id'], unique=False)
    op.create_index(op.f('ix_arko_projects_slug'), 'arko_projects', ['slug'], unique=True)
    op.create_index(op.f('ix_appointments_assigned_staff_id'), 'appointments', ['assigned_staff_id'], unique=False)
    op.drop_constraint('fk_doctors_clinic_id', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'doctors', ['clinic_id'], ['id'])
    op.drop_column('doctors', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('fk_doctors_clinic_id', 'doctors', 'doctors', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_appointments_assigned_staff_id'), table_name='appointments')
    op.drop_index(op.f('ix_arko_projects_slug'), table_name='arko_projects')
    op.drop_index(op.f('ix_arko_projects_id'), table_name='arko_projects')
    op.drop_table('arko_projects')
    op.drop_index(op.f('ix_arko_posts_slug'), table_name='arko_posts')
    op.drop_index(op.f('ix_arko_posts_id'), table_name='arko_posts')
    op.drop_table('arko_posts')
    # ### end Alembic commands ###
