"""add_theme_colors

Revision ID: 18ea8018026e
Revises: 3f06a7f9db94
Create Date: 2025-12-03 06:18:01.051655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ea8018026e'
down_revision = '3f06a7f9db94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('theme_body_bg_color', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('theme_container_bg_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'theme_container_bg_color')
    op.drop_column('doctors', 'theme_body_bg_color')
    # ### end Alembic commands ###

