"""Add cycle predictor tables

Revision ID: 1e4157f45955
Revises: 0e3cbb9671c3
Create Date: 2025-12-23 00:40:22.943998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4157f45955'
down_revision = '0e3cbb9671c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_logs_doctor_id'), 'cycle_logs', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_cycle_logs_id'), 'cycle_logs', ['id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('flow_intensity', sa.String(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_doctor_id'), 'symptom_logs', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_id'), 'symptom_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptom_logs_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_doctor_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_cycle_logs_id'), table_name='cycle_logs')
    op.drop_index(op.f('ix_cycle_logs_doctor_id'), table_name='cycle_logs')
    op.drop_table('cycle_logs')
    # ### end Alembic commands ###

