"""add blog_slug to services

Revision ID: 2b160e6b54cc
Revises: 4574923ca302
Create Date: 2025-12-18 20:09:03.297209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b160e6b54cc'
down_revision = '4574923ca302'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery_images', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('services', sa.Column('blog_slug', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_services_blog_post_id'), 'services', type_='foreignkey')
    op.drop_column('services', 'blog_post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('blog_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_services_blog_post_id'), 'services', 'blog_posts', ['blog_post_id'], ['id'])
    op.drop_column('services', 'blog_slug')
    op.alter_column('gallery_images', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###

