"""point_tenant_module_to_doctors

Revision ID: 3986a8974231
Revises: 0bfb35f37651
Create Date: 2025-11-27 22:56:48.020374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3986a8974231'
down_revision = '0bfb35f37651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_modules') as batch_op:
        # batch_op.drop_constraint('tenant_modules_tenant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_tenant_modules_doctors', 'doctors', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_modules') as batch_op:
        batch_op.drop_constraint('fk_tenant_modules_doctors', type_='foreignkey')
        batch_op.create_foreign_key('tenant_modules_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###

