"""add_mega_menu_fields_to_blog_posts

Revision ID: 4ece138b14a7
Revises: 18ea8018026e
Create Date: 2025-12-03 11:41:46.648746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece138b14a7'
down_revision = '18ea8018026e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('is_in_menu', sa.Boolean(), nullable=True))
    op.add_column('blog_posts', sa.Column('menu_weight', sa.Integer(), nullable=True))
    op.add_column('blog_posts', sa.Column('menu_icon', sa.String(), nullable=True))
    op.create_index(op.f('ix_blog_posts_is_in_menu'), 'blog_posts', ['is_in_menu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_posts_is_in_menu'), table_name='blog_posts')
    op.drop_column('blog_posts', 'menu_icon')
    op.drop_column('blog_posts', 'menu_weight')
    op.drop_column('blog_posts', 'is_in_menu')
    # ### end Alembic commands ###

