"""add medical_report_content

Revision ID: 64e30efabce1
Revises: cf952c35e489
Create Date: 2026-03-25 05:37:29.772657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e30efabce1'
down_revision = 'add_onboarding_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'habits_smoking')
    op.drop_column('consultations', 'habits_substance_use')
    op.drop_column('consultations', 'habits_alcohol')
    op.drop_column('consultations', 'habits_physical_activity')
    op.drop_index('idx_push_subs_endpoint', table_name='push_subscriptions', postgresql_where='(endpoint IS NOT NULL)')
    op.drop_index('idx_push_subs_token', table_name='push_subscriptions', postgresql_where='(token IS NOT NULL)')
    op.drop_constraint('push_subscriptions_endpoint_key', 'push_subscriptions', type_='unique')
    op.drop_constraint('push_subscriptions_token_key', 'push_subscriptions', type_='unique')
    op.create_index(op.f('ix_push_subscriptions_token'), 'push_subscriptions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_subscriptions_token'), table_name='push_subscriptions')
    op.create_unique_constraint('push_subscriptions_token_key', 'push_subscriptions', ['token'])
    op.create_unique_constraint('push_subscriptions_endpoint_key', 'push_subscriptions', ['endpoint'])
    op.create_index('idx_push_subs_token', 'push_subscriptions', ['token'], unique=False, postgresql_where='(token IS NOT NULL)')
    op.create_index('idx_push_subs_endpoint', 'push_subscriptions', ['endpoint'], unique=False, postgresql_where='(endpoint IS NOT NULL)')
    op.add_column('consultations', sa.Column('habits_physical_activity', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('consultations', sa.Column('habits_alcohol', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('consultations', sa.Column('habits_substance_use', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('consultations', sa.Column('habits_smoking', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
