"""add_cycle_user_recovery_fields

Revision ID: 6d48c3ecea69
Revises: 3891b5aa1eac
Create Date: 2025-12-24 17:03:08.360296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d48c3ecea69'
down_revision = '3891b5aa1eac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle_users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('cycle_users', sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle_users', 'reset_password_expires')
    op.drop_column('cycle_users', 'reset_password_token')
    # ### end Alembic commands ###

