"""ensure_cycle_tables

Revision ID: 9c8c129fd7ae
Revises: c5a918b1269d
Create Date: 2025-12-24 05:37:06.973238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8c129fd7ae'
down_revision = 'c5a918b1269d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle_logs', sa.Column('cycle_user_id', sa.Integer(), nullable=True))
    op.alter_column('cycle_logs', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_cycle_logs_cycle_user_id'), 'cycle_logs', ['cycle_user_id'], unique=False)
    op.create_foreign_key(None, 'cycle_logs', 'cycle_users', ['cycle_user_id'], ['id'])
    op.drop_constraint('cycle_users_email_key', 'cycle_users', type_='unique')
    op.drop_index('ix_cycle_users_email', table_name='cycle_users')
    op.create_index(op.f('ix_cycle_users_email'), 'cycle_users', ['email'], unique=True)
    op.add_column('symptom_logs', sa.Column('cycle_user_id', sa.Integer(), nullable=True))
    op.alter_column('symptom_logs', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_symptom_logs_cycle_user_id'), 'symptom_logs', ['cycle_user_id'], unique=False)
    op.create_foreign_key(None, 'symptom_logs', 'cycle_users', ['cycle_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.drop_index(op.f('ix_symptom_logs_cycle_user_id'), table_name='symptom_logs')
    op.alter_column('symptom_logs', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('symptom_logs', 'cycle_user_id')
    op.drop_index(op.f('ix_cycle_users_email'), table_name='cycle_users')
    op.create_index('ix_cycle_users_email', 'cycle_users', ['email'], unique=False)
    op.create_unique_constraint('cycle_users_email_key', 'cycle_users', ['email'])
    op.drop_constraint(None, 'cycle_logs', type_='foreignkey')
    op.drop_index(op.f('ix_cycle_logs_cycle_user_id'), table_name='cycle_logs')
    op.alter_column('cycle_logs', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('cycle_logs', 'cycle_user_id')
    # ### end Alembic commands ###

