"""add profile_image_border to doctor

Revision ID: 9d7a7481285d
Revises: 42ed74831021
Create Date: 2026-01-03 14:05:33.349594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7a7481285d'
down_revision = '42ed74831021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('profile_image_border', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'profile_image_border')
    # ### end Alembic commands ###

