"""Add image_url to notifications

Revision ID: aec3f1c116ba
Revises: 0b8315d53f8f
Create Date: 2026-04-05 19:22:42.103257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec3f1c116ba'
down_revision = '0b8315d53f8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'card_shadow',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('doctors', 'container_shadow',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('notification_logs', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_notification_logs_recipient_email_direct'), 'notification_logs', ['recipient_email_direct'], unique=False)
    op.add_column('notification_rules', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_patients_doctor_id'), 'patients', ['doctor_id'], unique=False)
    op.add_column('pending_notifications', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_pending_notifications_recipient_email_direct'), 'pending_notifications', ['recipient_email_direct'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_notifications_recipient_email_direct'), table_name='pending_notifications')
    op.drop_column('pending_notifications', 'image_url')
    op.drop_index(op.f('ix_patients_doctor_id'), table_name='patients')
    op.drop_column('notification_rules', 'image_url')
    op.drop_index(op.f('ix_notification_logs_recipient_email_direct'), table_name='notification_logs')
    op.drop_column('notification_logs', 'image_url')
    op.alter_column('doctors', 'container_shadow',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('doctors', 'card_shadow',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###

