"""Add consultations table

Revision ID: cf00f917cb5b
Revises: d3790118d2b2
Create Date: 2025-11-30 06:37:54.910285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf00f917cb5b'
down_revision = 'd3790118d2b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_ci', sa.String(), nullable=True),
    sa.Column('patient_age', sa.String(), nullable=True),
    sa.Column('patient_phone', sa.String(), nullable=True),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('family_history_mother', sa.Text(), nullable=True),
    sa.Column('family_history_father', sa.Text(), nullable=True),
    sa.Column('personal_history', sa.Text(), nullable=True),
    sa.Column('supplements', sa.Text(), nullable=True),
    sa.Column('surgical_history', sa.Text(), nullable=True),
    sa.Column('obstetric_history_summary', sa.Text(), nullable=True),
    sa.Column('functional_exam_summary', sa.Text(), nullable=True),
    sa.Column('habits_summary', sa.Text(), nullable=True),
    sa.Column('physical_exam', sa.Text(), nullable=True),
    sa.Column('ultrasound', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('history_number', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###

