"""add_social_media_fields

Revision ID: d3790118d2b2
Revises: 645ef5e75325
Create Date: 2025-11-28 14:22:40.034438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3790118d2b2'
down_revision = '645ef5e75325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('social_youtube', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('social_instagram', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('social_tiktok', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('social_x', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('social_facebook', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'social_facebook')
    op.drop_column('doctors', 'social_x')
    op.drop_column('doctors', 'social_tiktok')
    op.drop_column('doctors', 'social_instagram')
    op.drop_column('doctors', 'social_youtube')
    # ### end Alembic commands ###

