"""add services_section_title to doctor

Revision ID: e5090d434b7f
Revises: 6160c7b9aef2
Create Date: 2025-12-08 18:49:31.089909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5090d434b7f'
down_revision = '6160c7b9aef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('services_section_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'services_section_title')
    # ### end Alembic commands ###

