"""add_doctor_id_to_preconsultation

Revision ID: f228bcf6d2e7
Revises: 6d48c3ecea69
Create Date: 2025-12-29 12:16:28.511979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f228bcf6d2e7'
down_revision = '6d48c3ecea69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual injection of missing operations
    op.add_column('preconsultation_questions', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'preconsultation_questions', 'doctors', ['doctor_id'], ['id'])
# # #     op.add_column('appointments', sa.Column('patient_dni', sa.String(), nullable=True))
# #     op.add_column('appointments', sa.Column('patient_age', sa.Integer(), nullable=True))
    op.alter_column('doctors', 'reset_password_expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'reset_password_expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
#     op.drop_column('appointments', 'patient_age')
# #     op.drop_column('appointments', 'patient_dni')
    # ### end Alembic commands ###

