"""add_cycle_notification_and_pregnancy_models

Revision ID: f96bde83783a
Revises: 7baf1dd5b34a
Create Date: 2026-01-14 20:54:36.891266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96bde83783a'
down_revision = '7baf1dd5b34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

