"""Add contact_email to doctor

Revision ID: fe81e612c6f6
Revises: 662eb2b34637
Create Date: 2025-12-02 16:19:08.223198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe81e612c6f6'
down_revision = '662eb2b34637'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('contact_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'contact_email')
    # ### end Alembic commands ###

